---

- name: Install Python
  gather_facts: no
  hosts: all
  pre_tasks:
    - name: Install python 2
      raw: apt-get install -qq python

- name: set up server
  user: root
  hosts: all
  roles:
    - { role: base, tags: ['base'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: hepdata-files, tags: ['hepdata-files'] }
    - { role: kvserver, tags: ['kvserver'] }
    - { role: proxy, tags: ['proxy'] }
    - { role: elastic, tags: ['elastic'] }
    - { role: aggregator, tags: ['aggregator'] }
