# vim:ft=ansible:
---
- group: name=hepdata

- user: name=hepdata group=hepdata

- file: path=/hepdata state=directory owner=hepdata group=hepdata mode=0755

- name: Upload data set
  synchronize: dest=/hepdata/data.zip src=../../data.zip

- name: Unzip dataset
  command: unzip data.zip
  args:
    chdir: /hepdata
    creates: /hepdata/data

- name: Upload hepdata-explore
  synchronize: 
    dest: /hepdata/hepdata-explore/
    src: ../../../../ # root directory of the project
    recursive: yes 
    delete: yes 
    rsync_opts: 
      - "--chown=hepdata:hepdata"
      - "--chmod=755"
  tags: [sync]
